# Generated by Django 5.0.6 on 2024-05-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionary',
            old_name='choices',
            new_name='choice',
        ),
    ]
